### ISSUE TITLE
300-1000MHz Balun

### ISSUE THREAD

**Issue by skytee** [travisgoodspeed/goodwatch#40]
Replace Johanson 0433BM15A0001 433MHz balun with Anaren B0310J50100AHF 300-1000MHz balun. Same dimensions, almost same pinout (do not connect pin 5 and 6).

**Comment by travisgoodspeed** [comment]
I'll be merging the new balun this week and ordering a new batch of boards for Shmoocon.  Let anyone with filtering advice speak now or forever hold his peace.

**Comment by mossmann** [comment]
There are some SAW filters that would be quite nice.  We may be able to find a series of SAW filters that includes a few different useful frequencies with the same footprint.  However, it would be a hard choice between wideband operation and narrowband operation in a specific band.

**Comment by mossmann** [comment]
By far the most significant out of band emissions are harmonics of the RF (twice the center frequency, three times, and so on).  The approach I used on YARD Stick One was to install a low pass filter designed for the 900 MHz band.  This effectively filters out all of the harmonics when using the upper half of the tuning range but only filters out some of the harmonics when using the lower half of the tuning range.  I think this is a pretty good compromise that allows wideband operation.  People who need a cleaner signal for a specific frequency in the lower half of the range (e.g. 433 MHz) would have to modify the board to add a different filter.  On YARD Stick One, this is perhaps a better solution than it would be on GoodWatch because it is easy to add an external filter onto the SMA connector, but I think it is worth considering.

**Comment by mossmann** [comment]
The Murata series of SAW filters that includes SF2136E (433 MHz) looks like a good option for a footprint that supports various useful parts (315 MHz, 433 MHz, 868 MHz, 902-928 MHz, and more).  (SM3030-6 footprint)

**Comment by travisgoodspeed** [comment]
Dusting off this issue for the GoodWatch30.  I think I'll use the same Anaren B0310J50100AHF as @mossmann suggests from the YardStick One as a balun.

For a wideband filter, the 0915LP15B026E (915MHz) and 0500LP15A500E (500MHz) low-pass filters from Johanson have identical layouts, with only a slight different in component height.

![image](https://user-images.githubusercontent.com/770671/38781589-725dab0e-40b5-11e8-997d-a7bbb3f6b341.png)

**Comment by travisgoodspeed** [comment]
This is now drafted into the GW30.  Closing issue.
